@q = support

@param = ?client=dict-chrome-ex&dj=1&ie=utf8&oe=utf8&dt=t&dt=bd&dt=ex&dt=rm&dt=at&dt=md&dt=ss&sl=auto&tl=zh-CN&q=

GET https://translate.googleapis.com/translate_tts{{param}}{{q}}

###

GET https://translate.googleapis.com/translate_tts?client=dict-chrome-ex&ie=utf8&sl=auto&tl=en&q=hello